name: event_kit
description: A simple library for implementing event subscription APIs. 
version: 0.1.1
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/event_kit

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  disposable: '>=0.3.0<0.4.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
